(cl:in-package #:double-ratchet)


(defgeneric sending-chain (ratchet))
(defgeneric receiving-chain (ratchet))
(defgeneric kdf (chain))
(defgeneric forward (chain bytes &optional length))
(defgeneric steps (chain))
(defgeneric (setf steps) (new-value chain))
(defgeneric key (chain))
(defgeneric (setf key) (new-value chain))
(defgeneric move-ratchet (ratchet &optional bytes))
(defgeneric next-key (ratchet &optional bytes))
(defgeneric constant (symmetric-key-ratchet))
(defgeneric symetric-key-ratchet (diffie-hellman-ratchet))
(defgeneric private-key (diffie-hellman-ratchet))
(defgeneric public-key (diffie-hellman-ratchet))
(defgeneric derive-public (diffie-hellman-ratchet))
(defgeneric derive-private (diffie-hellman-ratchet))
(defgeneric long-term-identity-key (client))
(defgeneric signed-pre-key (client))
(defgeneric extended-triple-diffie-hellman (this-client other-client))
(defgeneric encrypt* (this-client other-client message))
(defgeneric decrypt* (this-client other-client cipher))
(defgeneric rotate-ratchet (this-client public-key))
